# Roles vendored in this source under ansible/roles/ + Galaxy Adaptix
roles:
  - name: ryokubaka.ludus_securityonion
  - name: ryokubaka.ludus_so_elastic_security
  - name: ryokubaka.ludus_so_elastic_agent
  - name: badsectorlabs.ludus_adaptix_c2
    src: https://github.com/badsectorlabs/ludus_adaptix_c2
    version: main

collections: []
